---

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
aptcachetime: 3600
ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false
